_target_: models.score_model_mlsb.Score_Model

seed: 42

data:
  ranking_train_set: null
  ranking_val_set: null

ranking_conf:
  num_workers: 1
  max_epochs: 4
  crop_size: 1200
  use_esm: True
  val_check_interval: 0.1
  ckpt_path: null
  output_dir: checkpoints/ranking_finetune_ckpts  # overridden by ranking_finetune.sh
  lr: 1e-4
  weight_decay: 0.0
  ranking_loss_weight: 0.5
  num_ranking_poses: 10
  buckets: 10

trainer:
  devices: 4

wandb:
  project: DFMDock2
  run_name: ranking_finetune_run
